spring.application.name=ecommercePrac

spring.security.user.name=nitish
spring.security.user.password=hello

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Magadh@987

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#logging.level.org.springframework.security=DEBUG
#logging.level.root=DEBUG
#logging.level.com.example=DEBUG
#logging.level.org.springframework.web=TRACE


#spring.app.jwtSecret=mySecretKey0987654567890dhgfhbndfgcjbvjbnmhgfhv
#spring.app.jwtExpirationMs=172800000

api.prefix=/api/v1

auth.token.expirationInMillis=3600000
auth.token.jwtSecret=34567865345678vbjhbvujhoiuhgvc678657vb8765fdfsxerwnfxhjs